name       : libfreeaptx
version    : 0.1.1
release    : 1
source     :
    - https://github.com/iamthehorker/libfreeaptx/archive/refs/tags/0.1.1.tar.gz : 7acf514446cae59585d9bc21e4f98f4a3856f4741c3a7a09d06e8ac5bf2f7315
license    : LGPL-2.1-or-later
component  : multimedia.codecs
summary    : Open Source implementation of Audio Processing Technology codec (aptX) derived from ffmpeg 4.0 project. libfreeaptx is based on version 0.2.0 of libopenaptx with the intent of continuing under a free license without the additional license restriction added to 0.2.1. 
description: |
    Open Source implementation of Audio Processing Technology codec (aptX) derived from ffmpeg 4.0 project. libfreeaptx is based on version 0.2.0 of libopenaptx with the intent of continuing under a free license without the additional license restriction added to 0.2.1.
    
    The initial version of libfreeaptx was reset to 0.1.0 to prevent confusion between the two projects.
replaces  :
    - libopenaptx
    - devel: libopenaptx-devel
environment: |
    export PREFIX=/usr
setup      : |
    sed -i "s|PREFIX |&?|" Makefile
    sed -i "s|CFLAGS |&?|" Makefile
    sed -i "s|LDFLAGS |&?|" Makefile
build      : |
    %make
install    : |
    %make_install
